version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: brazil_sports_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: brazil_sports
    ports:
      - "5433:5432"

volumes:
  postgres_data: